In [1]:
import graphlab

In [8]:
matchups = graphlab.SFrame.read_csv("2016_yahoo_matchups_week1-7.csv",delimiter='|')
weeks_elapsed = 7

Finished parsing file /Users/lukechu/Desktop/Pycharm/YahooFF2/2016_yahoo_matchups_week1-7.csv

Parsing completed. Parsed 35 lines in 0.039366 secs.

------------------------------------------------------
Inferred types from first 100 line(s) of file as
column_type_hints=[int,str,float,float,str,float,float,str,int]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------

Finished parsing file /Users/lukechu/Desktop/Pycharm/YahooFF2/2016_yahoo_matchups_week1-7.csv

Parsing completed. Parsed 35 lines in 0.018169 secs.

In [3]:
matchups.head()

Columns:
	Week	int
	TeamOne	str
	ProjectedScoreOne	float
	ScoreOne	float
	Winner	str
	ScoreTwo	float
	ProjectedScoreTwo	float
	TeamTwo	str
	Year	int

Rows: 10

Data:
+------+--------------------+-------------------+----------+--------+----------+
| Week |      TeamOne       | ProjectedScoreOne | ScoreOne | Winner | ScoreTwo |
+------+--------------------+-------------------+----------+--------+----------+
|  1   |  The Golden Yogis  |       107.69      |  102.2   |   <    |  149.46  |
|  1   | In TyGod we Trust  |       109.61      |  90.46   |   <    |  108.44  |
|  1   | dicksoutforharambe |       107.68      |  96.92   |   <    |  112.56  |
|  1   |      Penguins      |       115.82      |  106.22  |   <    |  134.9   |
|  1   |    Sit4Anthems     |       106.49      |   73.1   |   <    |  118.16  |
|  2   |  The Golden Yogis  |       106.49      |   84.2   |   <    |  110.16  |
|  2   |   Clippernation    |       130.55      |  111.52  |   <    |  123.86  |
|  2   | dicksoutforharambe |       103.34      |  104.36  |   >    |  101.46  |
|  2   |      Penguins      |       117.62      |  117.62  |   >    |  102.52  |
|  2   |    Sit4Anthems     |       104.85      |  117.76  |   >    |  92.92   |
+------+--------------------+-------------------+----------+--------+----------+
+-------------------+-------------------+------+
| ProjectedScoreTwo |      TeamTwo      | Year |
+-------------------+-------------------+------+
|       120.48      |   Clippernation   | 2016 |
|       109.49      |       Team 8      | 2016 |
|       114.6       | NomoneyforRedzone | 2016 |
|       114.46      |     Romosexual    | 2016 |
|       98.82       |   theoutoftowner  | 2016 |
|       112.87      | In TyGod we Trust | 2016 |
|       99.84       |   theoutoftowner  | 2016 |
|       110.47      |       Team 8      | 2016 |
|       111.9       | NomoneyforRedzone | 2016 |
|       105.34      |     Romosexual    | 2016 |
+-------------------+-------------------+------+
[10 rows x 9 columns]

In [4]:
# sort by score per week
matchup_week_score = {}

for i in range(1, weeks_elapsed+1): 
    matchup_week_score[i] = matchups[matchups["Week"]==i][["TeamOne", "ProjectedScoreOne", "ScoreOne" ]] # alternatively matchups[["Week"], ...].filter_by(1, "Week")
    matchup_week_score[i].rename({"TeamOne":"Team", "ProjectedScoreOne":"ProjectedScore", "ScoreOne":"Score"})
    
    # collision possible, but there are only 16 weeks
    matchup_week_score[i + 20] = matchups[matchups["Week"]==i][["TeamTwo", "ProjectedScoreTwo", "ScoreTwo" ]] # alternatively matchups[["Week"], ...].filter_by(1, "Week")
    matchup_week_score[i + 20].rename({"TeamTwo":"Team", "ProjectedScoreTwo":"ProjectedScore", "ScoreTwo":"Score"})

    matchup_week_score[i] = matchup_week_score[i].append(matchup_week_score[i+20])
    # remember that a column is an SArray (and a row is a dict)
    # alternatively (would be longer) could use .add_row_number, .rename, and reorder column to be last column
    matchup_week_score[i] = matchup_week_score[i].sort(["Score"]).add_column(graphlab.SArray(range(0,matchup_week_score[i].num_rows())), name ="NumberBeaten")

matchup_week_score

{1: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float
 	NumberBeaten	int

 Rows: 10

 Data:
 +--------------------+----------------+--------+--------------+
 |        Team        | ProjectedScore | Score  | NumberBeaten |
 +--------------------+----------------+--------+--------------+
 |    Sit4Anthems     |     106.49     |  73.1  |      0       |
 | In TyGod we Trust  |     109.61     | 90.46  |      1       |
 | dicksoutforharambe |     107.68     | 96.92  |      2       |
 |  The Golden Yogis  |     107.69     | 102.2  |      3       |
 |      Penguins      |     115.82     | 106.22 |      4       |
 |       Team 8       |     109.49     | 108.44 |      5       |
 | NomoneyforRedzone  |     114.6      | 112.56 |      6       |
 |   theoutoftowner   |     98.82      | 118.16 |      7       |
 |     Romosexual     |     114.46     | 134.9  |      8       |
 |   Clippernation    |     120.48     | 149.46 |      9       |
 +--------------------+----------------+--------+--------------+
 [10 rows x 4 columns], 2: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float
 	NumberBeaten	int

 Rows: 10

 Data:
 +--------------------+----------------+--------+--------------+
 |        Team        | ProjectedScore | Score  | NumberBeaten |
 +--------------------+----------------+--------+--------------+
 |  The Golden Yogis  |     106.49     |  84.2  |      0       |
 |     Romosexual     |     105.34     | 92.92  |      1       |
 |       Team 8       |     110.47     | 101.46 |      2       |
 | NomoneyforRedzone  |     111.9      | 102.52 |      3       |
 | dicksoutforharambe |     103.34     | 104.36 |      4       |
 | In TyGod we Trust  |     112.87     | 110.16 |      5       |
 |   Clippernation    |     130.55     | 111.52 |      6       |
 |      Penguins      |     117.62     | 117.62 |      7       |
 |    Sit4Anthems     |     104.85     | 117.76 |      8       |
 |   theoutoftowner   |     99.84      | 123.86 |      9       |
 +--------------------+----------------+--------+--------------+
 [10 rows x 4 columns], 3: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float
 	NumberBeaten	int

 Rows: 10

 Data:
 +--------------------+----------------+--------+--------------+
 |        Team        | ProjectedScore | Score  | NumberBeaten |
 +--------------------+----------------+--------+--------------+
 |   theoutoftowner   |     108.8      | 57.64  |      0       |
 |       Team 8       |     110.63     | 69.28  |      1       |
 | dicksoutforharambe |     103.6      |  70.9  |      2       |
 |    Sit4Anthems     |     102.62     | 82.36  |      3       |
 | NomoneyforRedzone  |     109.98     | 113.1  |      4       |
 |   Clippernation    |     128.73     | 116.58 |      5       |
 |      Penguins      |     112.08     | 117.44 |      6       |
 |  The Golden Yogis  |     107.89     | 122.34 |      7       |
 | In TyGod we Trust  |     99.12      | 128.88 |      8       |
 |     Romosexual     |     117.56     | 150.74 |      9       |
 +--------------------+----------------+--------+--------------+
 [10 rows x 4 columns], 4: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float
 	NumberBeaten	int

 Rows: 10

 Data:
 +--------------------+----------------+--------+--------------+
 |        Team        | ProjectedScore | Score  | NumberBeaten |
 +--------------------+----------------+--------+--------------+
 |   theoutoftowner   |     114.03     | 72.82  |      0       |
 | NomoneyforRedzone  |     102.62     | 98.62  |      1       |
 |  The Golden Yogis  |     108.3      | 99.44  |      2       |
 |   Clippernation    |     126.83     |  99.7  |      3       |
 |     Romosexual     |     107.64     | 105.46 |      4       |
 | In TyGod we Trust  |     95.89      | 110.7  |      5       |
 |      Penguins      |     105.88     | 112.28 |      6       |
 |    Sit4Anthems     |     110.76     | 117.88 |      7       |
 | dicksoutforharambe |     113.75     | 128.76 |      8       |
 |       Team 8       |     118.26     | 142.82 |      9       |
 +--------------------+----------------+--------+--------------+
 [10 rows x 4 columns], 5: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float
 	NumberBeaten	int

 Rows: 10

 Data:
 +--------------------+----------------+--------+--------------+
 |        Team        | ProjectedScore | Score  | NumberBeaten |
 +--------------------+----------------+--------+--------------+
 |   Clippernation    |     76.54      |  72.3  |      0       |
 |   theoutoftowner   |     109.05     |  76.7  |      1       |
 |    Sit4Anthems     |     109.44     | 84.42  |      2       |
 | NomoneyforRedzone  |     109.56     | 94.96  |      3       |
 |       Team 8       |     112.33     | 102.34 |      4       |
 | dicksoutforharambe |     110.28     | 103.08 |      5       |
 |  The Golden Yogis  |     111.85     | 119.86 |      6       |
 | In TyGod we Trust  |     102.6      | 119.9  |      7       |
 |     Romosexual     |     107.1      | 139.28 |      8       |
 |      Penguins      |     115.92     | 140.78 |      9       |
 +--------------------+----------------+--------+--------------+
 [10 rows x 4 columns], 6: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float
 	NumberBeaten	int

 Rows: 10

 Data:
 +--------------------+----------------+--------+--------------+
 |        Team        | ProjectedScore | Score  | NumberBeaten |
 +--------------------+----------------+--------+--------------+
 | In TyGod we Trust  |     116.67     | 70.36  |      0       |
 | dicksoutforharambe |     110.35     |  71.0  |      1       |
 |   Clippernation    |     118.06     | 94.98  |      2       |
 | NomoneyforRedzone  |     112.02     | 99.06  |      3       |
 |    Sit4Anthems     |     105.89     | 100.94 |      4       |
 |   theoutoftowner   |     119.35     | 101.72 |      5       |
 |       Team 8       |     110.58     | 110.14 |      6       |
 |  The Golden Yogis  |     105.16     | 115.36 |      7       |
 |     Romosexual     |     105.41     | 119.18 |      8       |
 |      Penguins      |     117.6      | 159.6  |      9       |
 +--------------------+----------------+--------+--------------+
 [10 rows x 4 columns], 7: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float
 	NumberBeaten	int

 Rows: 10

 Data:
 +--------------------+----------------+--------+--------------+
 |        Team        | ProjectedScore | Score  | NumberBeaten |
 +--------------------+----------------+--------+--------------+
 | In TyGod we Trust  |     107.92     | 80.44  |      0       |
 |       Team 8       |     112.76     | 87.88  |      1       |
 |    Sit4Anthems     |     100.58     | 97.24  |      2       |
 |      Penguins      |     111.2      | 103.38 |      3       |
 |  The Golden Yogis  |     104.47     | 109.58 |      4       |
 |     Romosexual     |     101.22     | 110.52 |      5       |
 | NomoneyforRedzone  |     108.0      | 115.74 |      6       |
 |   Clippernation    |     101.35     | 116.02 |      7       |
 |   theoutoftowner   |     103.04     | 116.94 |      8       |
 | dicksoutforharambe |     110.05     | 121.72 |      9       |
 +--------------------+----------------+--------+--------------+
 [10 rows x 4 columns], 21: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float

 Rows: Unknown

 Data:
 +-------------------+----------------+--------+
 |        Team       | ProjectedScore | Score  |
 +-------------------+----------------+--------+
 |   Clippernation   |     120.48     | 149.46 |
 |       Team 8      |     109.49     | 108.44 |
 | NomoneyforRedzone |     114.6      | 112.56 |
 |     Romosexual    |     114.46     | 134.9  |
 |   theoutoftowner  |     98.82      | 118.16 |
 +-------------------+----------------+--------+
 [? rows x 3 columns]
 Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
 You can use sf.materialize() to force materialization., 22: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float

 Rows: Unknown

 Data:
 +-------------------+----------------+--------+
 |        Team       | ProjectedScore | Score  |
 +-------------------+----------------+--------+
 | In TyGod we Trust |     112.87     | 110.16 |
 |   theoutoftowner  |     99.84      | 123.86 |
 |       Team 8      |     110.47     | 101.46 |
 | NomoneyforRedzone |     111.9      | 102.52 |
 |     Romosexual    |     105.34     | 92.92  |
 +-------------------+----------------+--------+
 [? rows x 3 columns]
 Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
 You can use sf.materialize() to force materialization., 23: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float

 Rows: Unknown

 Data:
 +--------------------+----------------+--------+
 |        Team        | ProjectedScore | Score  |
 +--------------------+----------------+--------+
 |     Romosexual     |     117.56     | 150.74 |
 | dicksoutforharambe |     103.6      |  70.9  |
 |   theoutoftowner   |     108.8      | 57.64  |
 |       Team 8       |     110.63     | 69.28  |
 | NomoneyforRedzone  |     109.98     | 113.1  |
 +--------------------+----------------+--------+
 [? rows x 3 columns]
 Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
 You can use sf.materialize() to force materialization., 24: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float

 Rows: Unknown

 Data:
 +--------------------+----------------+--------+
 |        Team        | ProjectedScore | Score  |
 +--------------------+----------------+--------+
 |      Penguins      |     105.88     | 112.28 |
 | dicksoutforharambe |     113.75     | 128.76 |
 |   theoutoftowner   |     114.03     | 72.82  |
 |       Team 8       |     118.26     | 142.82 |
 | NomoneyforRedzone  |     102.62     | 98.62  |
 +--------------------+----------------+--------+
 [? rows x 3 columns]
 Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
 You can use sf.materialize() to force materialization., 25: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float

 Rows: Unknown

 Data:
 +--------------------+----------------+--------+
 |        Team        | ProjectedScore | Score  |
 +--------------------+----------------+--------+
 |    Sit4Anthems     |     109.44     | 84.42  |
 |      Penguins      |     115.92     | 140.78 |
 | dicksoutforharambe |     110.28     | 103.08 |
 |       Team 8       |     112.33     | 102.34 |
 |   theoutoftowner   |     109.05     |  76.7  |
 +--------------------+----------------+--------+
 [? rows x 3 columns]
 Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
 You can use sf.materialize() to force materialization., 26: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float

 Rows: Unknown

 Data:
 +----------------+----------------+--------+
 |      Team      | ProjectedScore | Score  |
 +----------------+----------------+--------+
 |   Romosexual   |     105.41     | 119.18 |
 |  Sit4Anthems   |     105.89     | 100.94 |
 |    Penguins    |     117.6      | 159.6  |
 | theoutoftowner |     119.35     | 101.72 |
 |     Team 8     |     110.58     | 110.14 |
 +----------------+----------------+--------+
 [? rows x 3 columns]
 Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
 You can use sf.materialize() to force materialization., 27: Columns:
 	Team	str
 	ProjectedScore	float
 	Score	float

 Rows: Unknown

 Data:
 +-------------------+----------------+--------+
 |        Team       | ProjectedScore | Score  |
 +-------------------+----------------+--------+
 | NomoneyforRedzone |     108.0      | 115.74 |
 |     Romosexual    |     101.22     | 110.52 |
 |    Sit4Anthems    |     100.58     | 97.24  |
 |      Penguins     |     111.2      | 103.38 |
 |   theoutoftowner  |     103.04     | 116.94 |
 +-------------------+----------------+--------+
 [? rows x 3 columns]
 Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
 You can use sf.materialize() to force materialization.}

In [9]:
# Calculate Expected Wins. EW = sum( # of opponents beaten each week ) / # of opponents

# For each team, group by number beaten
#simple way to initalize new SFrame with same structure and skip an append
matchup_scores = matchup_week_score[1]
for i in range(2, weeks_elapsed + 1):
    matchup_scores = matchup_scores.append(matchup_week_score[i])

# group by sum of total Beaten    
teams_beaten = matchup_scores.groupby(key_columns = "Team", operations = {"TotalBeaten": graphlab.aggregate.SUM("NumberBeaten")})
teams_beaten.add_column(teams_beaten["TotalBeaten"]/ 9, "ExpectedWins") # 9 opponents
teams_beaten["TotalBeaten"] = teams_beaten["TotalBeaten"]/ weeks_elapsed # 
teams_beaten.rename({"TotalBeaten": "AvgBeatPerWeek"})
teams_beaten.sort("ExpectedWins", ascending = False)

# SFrames don't have round function?

Columns:
	Team	str
	AvgBeatPerWeek	float
	ExpectedWins	float

Rows: 10

Data:
+--------------------+----------------+---------------+
|        Team        | AvgBeatPerWeek |  ExpectedWins |
+--------------------+----------------+---------------+
|      Penguins      | 6.28571428571  | 4.88888888889 |
|     Romosexual     | 6.14285714286  | 4.77777777778 |
|   Clippernation    | 4.57142857143  | 3.55555555556 |
| dicksoutforharambe | 4.42857142857  | 3.44444444444 |
|   theoutoftowner   | 4.28571428571  | 3.33333333333 |
|  The Golden Yogis  | 4.14285714286  | 3.22222222222 |
|       Team 8       |      4.0       | 3.11111111111 |
| In TyGod we Trust  | 3.71428571429  | 2.88888888889 |
|    Sit4Anthems     | 3.71428571429  | 2.88888888889 |
| NomoneyforRedzone  | 3.71428571429  | 2.88888888889 |
+--------------------+----------------+---------------+
[10 rows x 3 columns]